server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:film
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
      show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  main:
    web-application-type: servlet
